apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.credentialsSecret.name }}
            namespace: {{ .Values.credentialsSecret.namespace }}
            key: access-key
          secretAccessKeySecretRef:
            name: {{ .Values.credentialsSecret.name }}
            namespace: {{ .Values.credentialsSecret.namespace }}
            key: secret-access-key
